const fa = document.getElementById('container')
const lis = Array.from(fa.getElementsByTagName('li'))
const webApi = lis.filter(v => v.dataset.tag && v.dataset.tag.includes('webapi'))
const list = webApi.map(v => v.dataset)
console.log(list.length)

const statusTypes = Array.from(new Set(list.map(v => v.status)))
console.log(JSON.stringify(statusTypes))

const obj = {}

for (const type of statusTypes) {
  obj[type] = list.filter(v => v.status === type).map(v => v.title)
}

console.log(JSON.stringify(obj))

const obj2 = {
  FPWD: [
    "webassembly javascript interface",
    "webassembly web api",
    "mediastreamtrack insertable media processing using streams",
    "editcontext api",
    "digital publishing accessibility api mappings 1.1",
    "webxr lighting estimation api level 1",
    "incremental font transfer",
    "webxr dom overlays module",
    "secure payment confirmation"
  ],
  WD: [
    "webgpu",
    "webxr depth sensing module",
    "webxr hit test module",
    "region capture",
    "resource timing level 2",
    "screen capture",
    "autoplay policy detection",
    "reporting api",
    "webdriver",
    "miniapp lifecycle",
    "web neural network api",
    "push api",
    "pointer events",
    "webxr augmented reality module - level 1",
    "geolocation sensor",
    "web share api",
    "navigation timing level 2",
    "gamepad",
    "battery status api",
    "webxr gamepads module - level 1",
    "high resolution time",
    "ambient light sensor",
    "screen wake lock api",
    "magnetometer",
    "pointer lock 2.0",
    "media capture from dom elements",
    "device posture api",
    "indexed database api 3.0",
    "payment handler api",
    "virtualkeyboard api",
    "the screen orientation api",
    "proximity sensor",
    "orientation sensor",
    "clipboard api and events",
    "selection api",
    "mediastreamtrack content hints",
    "server timing",
    "image resource",
    "file api",
    "mediastream recording",
    "mediastream image capture",
    "permissions policy",
    "input events level 1",
    "deviceorientation event specification",
    "network error logging",
    "mediastream capture scenarios",
    "audio processing api"
  ],
  CR: [
    "webxr device api",
    "user timing",
    "performance timeline",
    "page visibility level 2",
    "webrtc priority control api",
    "service workers 1",
    "remote playback api",
    "ui events keyboardevent code values",
    "ui events keyboardevent key values",
    "resource timing level 1"
  ],
  CRD: [
    "generic sensor api",
    "media capture and streams",
    "audio output devices api",
    "accelerometer",
    "gyroscope",
    "identifiers for webrtc's statistics api",
    "presentation api"
  ],
  PR: [
    "geolocation api",
    "payment request api",
    "cooperative scheduling of background tasks"
  ],
  REC: [
    "web audio api",
    "web storage (second edition)",
    "server-sent events",
    "html5 web messaging",
    "webrtc 1.0: real-time communication between browsers",
    "json-ld 1.0 processing algorithms and api",
    "progress events",
    "web notifications",
    "webassembly javascript interface",
    "high resolution time",
    "high resolution time level 2",
    "pointer events",
    "pointer events",
    "user timing",
    "user timing level 2",
    "widget interface",
    "webdriver",
    "html media capture",
    "indexed database api 2.0",
    "encrypted media extensions",
    "web cryptography api",
    "webidl level 1",
    "media source extensions™",
    "geolocation api specification 2nd edition",
    "pointer lock",
    "vibration api (second edition)",
    "indexed database api",
    "metadata api for media resources 1.0",
    "performance timeline",
    "page visibility (second edition)",
    "touch events",
    "navigation timing"
  ],
  DNOTE: [
    "strings on the web: language and direction metadata"
  ],
  DISC: [
    "media capture depth stream extensions"
  ],
  NOTE: [
    "worklets level 1",
    "audio eq cookbook",
    "web workers",
    "the websocket api",
    "motion sensors explainer",
    "geolocation api specification level 2",
    "findtext api",
    "network service discovery",
    "url",
    "streams api",
    "xmlhttprequest level 1",
    "iso bmff byte stream format",
    "mpeg-2 ts byte stream format",
    "mpeg audio byte stream format",
    "media source extensions byte stream format registry",
    "webm byte stream format",
    "encrypted media extensions stream format registry",
    "webm stream format",
    "\"cenc\" initialization data format",
    "\"keyids\" initialization data format",
    "encrypted media extensions initialization data format registry",
    "iso common encryption ('cenc') protection scheme for iso base media file format stream format",
    "\"webm\" initialization data format",
    "frame timing",
    "input method editor api",
    "quota management api",
    "timing control for script-based animations",
    "runtime and security model for web applications",
    "tcp and udp socket api",
    "the app: url scheme",
    "task scheduler api specification",
    "permissions for device api access",
    "web nfc api",
    "contacts manager api",
    "web telephony api",
    "messaging api",
    "fullscreen",
    "wake lock: use cases",
    "file api: directories and system",
    "file api: writer",
    "the network information api",
    "review of apps that use network information",
    "calendar api",
    "pick media intent",
    "pick contacts intent",
    "web intents addendum - local services",
    "the system information api",
    "the messaging api",
    "touch events extensions",
    "selectors api level 2",
    "web intents",
    "web audio processing: use cases and requirements",
    "web api design cookbook",
    "rdf api",
    "rdfa api",
    "rdf interfaces",
    "web application privacy best practices",
    "mediastream processing api",
    "the media capture api",
    "programmable http caching and serving",
    "web sql database",
    "device apis requirements",
    "offline web applications"
  ]
}
